name: Deploy to EC2

on:
  push:
    branches:
      - main 
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate random tag
      id: generate_tag
      run: |
        # Generate a random 6-digit hexadecimal tag
        TAG=$(openssl rand -hex 3)
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      run: |
        docker build -t niznaor/doggo-app:${{ env.TAG }} ./backend
        
    - name: Push Docker image to Docker Hub
      run: |
        docker push niznaor/doggo-app:${{ env.TAG }}
        
    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker ps -q -f name=doggo-app | grep -q . && docker stop doggo-app || echo "No running container found with the name doggo-app"
          docker pull niznaor/doggo-app:${{ env.TAG }}
          docker run -d --name doggo-app -p 5000:5000 niznaor/doggo-app:${{ env.TAG }}
